# Generated by Django 4.2.1 on 2023-05-28 16:16

from django.db import migrations


def create_facts(apps, schema_editor):
    Fact = apps.get_model('facts', 'Fact')
    Fact.objects.create(fact='Chuck Norris puede dividir entre cero.')
    Fact.objects.create(
        fact="Hay 1424 cosas en una habitación promedio con las que Chuck Norris podría matarte. Incluyendo la habitación en sí.")
    Fact.objects.create(
        fact="Chuck Norris es la medida del sistema internacional del dolor.")
    Fact.objects.create(
        fact="Chuck Norris ganó un concurso sobre permanecer debajo del agua y ganó. Cabe destacar que su contrincante era pez.")
    Fact.objects.create(
        fact="Las lágrimas de Chuck Norris curan el cáncer. Lástima que jamás haya llorado.")
    Fact.objects.create(
        fact="Chuck Norris dona sangre a menudo. Pero rara vez es la suya.")
    Fact.objects.create(
        fact="La gente usa pijamas de Superman. Superman usa pijamas de Chuck Norris.")


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_facts),
    ]
