# Generated by Django 4.2.1 on 2023-05-28 16:16

from django.db import migrations


def create_facts(apps, schema_editor):
    Fact = apps.get_model('facts', 'Fact')
    Fact.objects.create(
        fact='Chuck Norris contó hasta el infinito. Dos veces.')
    Fact.objects.create(
        fact="Chuck Norris puede dividir por cero.")
    Fact.objects.create(
        fact="Chuck Norris puede reproducir un CD en un tocadiscos.")
    Fact.objects.create(
        fact="Chuck Norris puede ganar al Sol en un juego de miradas.")
    Fact.objects.create(
        fact="Chuck Norris dona sangre a menudo. Pero rara vez es la suya.")


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_facts),
    ]
